/* Generated by Yosys 0.7+281 (git sha1 d38a64b, gcc 4.9.2-10 -fPIC -Os) */

(* src = "ParaleloSerial.v:4" *)
module ParaleloSerial(clk, reset, enb, clk8, entrada, salida);
  (* src = "ParaleloSerial.v:25" *)
  wire [3:0] _000_;
  (* src = "ParaleloSerial.v:25" *)
  wire [3:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "ParaleloSerial.v:22" *)
  wire _063_;
  wire [1:0] _064_;
  wire _065_;
  (* src = "ParaleloSerial.v:22" *)
  wire [31:0] _066_;
  (* src = "ParaleloSerial.v:22" *)
  wire _067_;
  (* src = "ParaleloSerial.v:30" *)
  wire [31:0] _068_;
  (* src = "ParaleloSerial.v:22|<techmap.v>:145" *)
  wire [7:0] _069_;
  (* src = "ParaleloSerial.v:22|<techmap.v>:145" *)
  wire [7:0] _070_;
  (* src = "ParaleloSerial.v:22|<techmap.v>:145" *)
  wire [7:0] _071_;
  (* src = "ParaleloSerial.v:22|<techmap.v>:145" *)
  wire [7:0] _072_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _073_;
  wire [31:0] _074_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _075_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _076_;
  (* src = "ParaleloSerial.v:30" *)
  wire [31:0] _077_;
  (* src = "ParaleloSerial.v:13" *)
  input clk;
  (* src = "ParaleloSerial.v:16" *)
  input clk8;
  (* src = "ParaleloSerial.v:19" *)
  reg [3:0] contador;
  (* src = "ParaleloSerial.v:14" *)
  input enb;
  (* src = "ParaleloSerial.v:17" *)
  input [7:0] entrada;
  (* src = "ParaleloSerial.v:15" *)
  input reset;
  (* src = "ParaleloSerial.v:18" *)
  output salida;
  NOT _078_ (
    .A(_002_),
    .Y(_006_)
  );
  NOT _079_ (
    .A(_003_),
    .Y(_007_)
  );
  NOT _080_ (
    .A(_021_),
    .Y(_008_)
  );
  NOT _081_ (
    .A(_032_),
    .Y(_009_)
  );
  NOT _082_ (
    .A(_005_),
    .Y(_010_)
  );
  NOT _083_ (
    .A(_011_),
    .Y(_012_)
  );
  NOT _084_ (
    .A(_049_),
    .Y(_014_)
  );
  NOR _085_ (
    .A(_021_),
    .B(_042_),
    .Y(_016_)
  );
  NAND _086_ (
    .A(_021_),
    .B(_014_),
    .Y(_018_)
  );
  NOR _087_ (
    .A(_021_),
    .B(_037_),
    .Y(_020_)
  );
  NOR _088_ (
    .A(_008_),
    .B(_046_),
    .Y(_022_)
  );
  NOR _089_ (
    .A(_020_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _090_ (
    .A(_007_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _091_ (
    .A(_003_),
    .B(_018_),
    .Y(_025_)
  );
  NOR _092_ (
    .A(_016_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _093_ (
    .A(_002_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _094_ (
    .A(_024_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _095_ (
    .A(_021_),
    .B(_044_),
    .Y(_029_)
  );
  NOR _096_ (
    .A(_008_),
    .B(_051_),
    .Y(_030_)
  );
  NOR _097_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _098_ (
    .A(_007_),
    .B(_031_),
    .Y(_033_)
  );
  NOR _099_ (
    .A(_021_),
    .B(_040_),
    .Y(_034_)
  );
  NOR _100_ (
    .A(_008_),
    .B(_048_),
    .Y(_035_)
  );
  NOR _101_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _102_ (
    .A(_003_),
    .B(_036_),
    .Y(_038_)
  );
  NOR _103_ (
    .A(_033_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _104_ (
    .A(_006_),
    .B(_039_),
    .Y(_041_)
  );
  NAND _105_ (
    .A(_009_),
    .B(_005_),
    .Y(_043_)
  );
  NOR _106_ (
    .A(_011_),
    .B(_043_),
    .Y(_045_)
  );
  NAND _107_ (
    .A(_028_),
    .B(_045_),
    .Y(_047_)
  );
  NOR _108_ (
    .A(_041_),
    .B(_047_),
    .Y(_004_)
  );
  NOR _109_ (
    .A(_006_),
    .B(_005_),
    .Y(_050_)
  );
  NOR _110_ (
    .A(_002_),
    .B(_010_),
    .Y(_052_)
  );
  NOT _111_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR _112_ (
    .A(_050_),
    .B(_052_),
    .Y(_054_)
  );
  NOR _113_ (
    .A(_011_),
    .B(_054_),
    .Y(_013_)
  );
  NOR _114_ (
    .A(_003_),
    .B(_053_),
    .Y(_055_)
  );
  NOT _115_ (
    .A(_055_),
    .Y(_056_)
  );
  NOR _116_ (
    .A(_007_),
    .B(_052_),
    .Y(_057_)
  );
  NOR _117_ (
    .A(_055_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _118_ (
    .A(_011_),
    .B(_058_),
    .Y(_015_)
  );
  NOR _119_ (
    .A(_008_),
    .B(_055_),
    .Y(_059_)
  );
  NOR _120_ (
    .A(_021_),
    .B(_056_),
    .Y(_060_)
  );
  NOR _121_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _122_ (
    .A(_011_),
    .B(_061_),
    .Y(_017_)
  );
  NAND _123_ (
    .A(_032_),
    .B(_012_),
    .Y(_062_)
  );
  NOR _124_ (
    .A(_060_),
    .B(_062_),
    .Y(_019_)
  );
  (* src = "ParaleloSerial.v:25" *)
  always @(posedge clk)
      contador[0] <= _000_[0];
  (* src = "ParaleloSerial.v:25" *)
  always @(posedge clk)
      contador[1] <= _000_[1];
  (* src = "ParaleloSerial.v:25" *)
  always @(posedge clk)
      contador[2] <= _000_[2];
  (* src = "ParaleloSerial.v:25" *)
  always @(posedge clk)
      contador[3] <= _000_[3];
  assign _002_ = contador[0];
  assign _003_ = contador[1];
  assign _021_ = contador[2];
  assign _032_ = contador[3];
  assign salida = _004_;
  assign _005_ = enb;
  assign _011_ = reset;
  assign _000_[0] = _013_;
  assign _000_[1] = _015_;
  assign _000_[2] = _017_;
  assign _000_[3] = _019_;
  assign _037_ = entrada[0];
  assign _040_ = entrada[1];
  assign _042_ = entrada[2];
  assign _044_ = entrada[3];
  assign _046_ = entrada[4];
  assign _048_ = entrada[5];
  assign _049_ = entrada[6];
  assign _051_ = entrada[7];
endmodule
